(function(){
  var currentScript=document.currentScript; var analytics=document.createElement('script'); analytics.src=new URL('analytics.js',currentScript&&currentScript.src||location.href).href; analytics.async=true; document.head.appendChild(analytics);
  var root=document.documentElement;
  document.querySelectorAll('[data-theme-toggle]').forEach(function(btn){btn.addEventListener('click',function(){var next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;try{localStorage.setItem('site-theme',next);}catch(e){} document.querySelectorAll('[data-theme-toggle]').forEach(function(x){x.setAttribute('aria-pressed',next==='dark');});});});
  document.querySelectorAll('[data-menu-toggle]').forEach(function(btn){btn.addEventListener('click',function(){var menu=document.getElementById(btn.dataset.menuToggle);var open=menu.classList.toggle('is-open');btn.setAttribute('aria-expanded',open);});});
  var reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;var items=document.querySelectorAll('.reveal');
  if(reduce){items.forEach(function(x){x.classList.add('is-visible');});}else if('IntersectionObserver' in window){var io=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target);}})},{threshold:.12});items.forEach(function(x){io.observe(x);});}else{items.forEach(function(x){x.classList.add('is-visible');});}
  document.querySelectorAll('[data-tabs]').forEach(function(group){var tabs=group.querySelectorAll('.price-tab'),panels=group.querySelectorAll('.price-panel');tabs.forEach(function(tab){tab.addEventListener('click',function(){tabs.forEach(function(x){x.classList.remove('is-active');x.setAttribute('aria-selected','false');});panels.forEach(function(x){x.classList.remove('is-active');});tab.classList.add('is-active');tab.setAttribute('aria-selected','true');var panel=group.querySelector('#'+tab.dataset.target);if(panel)panel.classList.add('is-active');});});});
  document.querySelectorAll('[data-filter-group]').forEach(function(group){var buttons=group.querySelectorAll('[data-filter]'),cards=document.querySelectorAll('[data-project]');buttons.forEach(function(btn){btn.addEventListener('click',function(){var value=btn.dataset.filter;buttons.forEach(function(x){x.classList.toggle('is-active',x===btn);x.setAttribute('aria-selected',x===btn);});cards.forEach(function(card){card.hidden=value!=='all'&&card.dataset.project!==value&&card.dataset.direction!==value;});});});});
  document.querySelectorAll('[data-faq]').forEach(function(btn){btn.addEventListener('click',function(){var panel=document.getElementById(btn.getAttribute('aria-controls'));var open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',!open);if(panel)panel.hidden=open;});});
  document.querySelectorAll('form[data-lead-form]').forEach(function(form){form.addEventListener('submit',function(e){e.preventDefault();if(!form.reportValidity())return;var button=form.querySelector('button[type=submit]'),status=form.querySelector('.form-status');var direction=(form.elements.direction&&form.elements.direction.value)||form.dataset.direction||'Общая заявка';var payload={name:form.elements.name.value.trim(),phone:form.elements.phone.value.trim(),message:'['+direction+'] '+form.elements.message.value.trim(),consent:Boolean(form.elements.consent.checked)};button.disabled=true;button.textContent='ОТПРАВЛЯЕМ...';fetch('https://d5d01eb689qn07cv0ocu.sax5b7yq.apigw.yandexcloud.net/api/website-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){if(!r.ok)throw Error();status.textContent='Заявка отправлена. Мы свяжемся с вами в рабочее время.';form.reset();button.textContent='ЗАЯВКА ОТПРАВЛЕНА';}).catch(function(){status.textContent='Не удалось отправить заявку. Позвоните нам: +7 (924) 231-04-78';button.disabled=false;button.textContent='ОТПРАВИТЬ ЗАЯВКУ';});});});
})();
